substitutions:
  _GCP_REGION: us-central1
  _ARTIFACT_REPOSITORY: ml-model-serving
  _IMAGE_NAME: ml-prediction-app
  _IMAGE_TAG: latest

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.prod
      - -t
      - ${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:${_IMAGE_TAG}
      - .

images:
  - ${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:${_IMAGE_TAG}

